version: "3"

services:
  api:
    build:
      context: .
      args:
        - ENV=dev
    environment:
      - ENV=dev
      - RR_WORKERS_NUM=1
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9000
    ports:
      - 80:8080
    volumes:
      - .:/app
